version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
